import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import localFont from "next/font/local";

import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import "../globals.css";
import Navbar from "@/components/navbar/navbar";

// ----------------------------------------------------------------------

const lineSeedTH = localFont({
  variable: "--font-line-seed-sans-th",
  src: [
    {
      path: "../../public/fonts/LINESeedSansTH_W_Th.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/LINESeedSansTH_W_Rg.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/LINESeedSansTH_W_Bd.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/LINESeedSansTH_W_XBd.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/LINESeedSansTH_W_He.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

// ----------------------------------------------------------------------

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang="en" data-theme="night" data-theme-mode="dark">
      <body className={`${lexend.variable} ${lineSeedTH.variable} antialiased`}>
        <div className="flex w-full flex-col">
          <NextIntlClientProvider>
            <Navbar />
            {children}
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  );
}
